### ISSUE TITLE
Crash when removing Gravestone Mod

### ISSUE THREAD

**Issue by AnonymousPuppy** [NightKosh/GraveStone-mod#130]
Using Forge .1240, a custom modpack, and Gravestone 2.11.1. I'm getting a startup crash as soon as I remove your mod. Adding it back in "fixes" the issue. 

Crash Report: http://pastebin.com/NF3u5Y7d

Please take a look at it whenever you can, thank you.

**Comment by NightKosh** [comment]
It looks like some of your mods required Mariculture API, which is missed..
