### ISSUE TITLE
Fog Glitchiness at Dawn and Sunset

### ISSUE THREAD

**Issue by da3dsoul** [NightKosh/GraveStone-mod#148]
This has been mentioned on the forums. Putting it here for documentation.

**Comment by da3dsoul** [comment]
I'll try to fix this.

**Comment by NightKosh** [comment]
All fog code placed in 3 classes
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/core/event/GSClientTickEventHandler.java
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/core/event/GSRenderEventHandler.java
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/tileentity/TileEntityGSGraveStone.java (update method)
