### ISSUE TITLE
Witchery Vampirism interaction

### ISSUE THREAD

**Issue by TheDrowElf** [NightKosh/GraveStone-mod#176]
When you play as a vampire with the Witchery mod, you can take damage that would normally kill you, and not die. This results in the player's inventory getting put into a grave while they are still alive. The fix for this should be as simple as changing the event from null health to death.

**Comment by superckl** [comment]
Just some info on the ramifications of this. If you are a vampire and get stuck in something that does repetitive damage (such as a Hardcore Ender Expansion node exploding),  you will generate a gravestone every time you are damaged. Depending on the rate of the damage, this could lead to 200+ gravestones being generated, all but one being empty.
