### ISSUE TITLE
Right-clickeable gravestones

### ISSUE THREAD

**Issue by NoireMann** [NightKosh/GraveStone-mod#192]
Could you please add Right-click (grave inventory opening) feature to your mod?

That would be very awesome!

**Comment by NightKosh** [comment]
It is already done.)) This feature will be available in next release.

https://github.com/NightKosh/GraveStone-mod/issues/149

**Comment by NoireMann** [comment]
Это будет доступно в версии 1.7.10?
Обязательно лопаты использовать? Может еще голыми руками можно будет?:3

Will it be possible on 1.7.10?

Is it necessary to use a shovel, or it is possible to right-hand on a gravestone?
