### ISSUE TITLE
No world-genned gravestone inventory on MCPC/Cauldron

### ISSUE THREAD

**Issue by sadris** [NightKosh/GraveStone-mod#40]
I am using cauldron-1.7.10-1.1207.01.187-server.jar and GraveStone 2.9.2. Gravestones will simply not drop anything on MCPC/Cauldron. I've opened the world-file in MCEdit and there isn't anything in the items NBT tag for gravestones.

**Comment by Adaptivity** [comment]
Cauldron мёртв. Можно закрывать.
