### ISSUE TITLE
Galacticraft compatibility

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/GraveStone-mod#41]
Store items in graves from Galacticraft slots.

**Comment by Mochnant** [comment]
This will be a great addition.  Any ETA on the feature?

**Comment by NightKosh** [comment]
hmm. It looks like i forget to close this task. All required changes was done in e61bf4645cf0c18cf708d255136ef2cac8c718eb commit.

**Comment by Mochnant** [comment]
Thanks!
